### ISSUE TITLE
Back-End - Corrupted Title with "<", ">" elements from sub-elements to <title>

### ISSUE THREAD

**Issue by TheWoodenMan** [HoldUpFjord/Link-Manager#24]
![image](https://user-images.githubusercontent.com/85075266/188282490-ecb6f770-1fe1-467a-b7e5-c5821c6a52e3.png)
with some sites, you can see on the image above, other sub tags are pulled in which corrupts the title.

We need to add logic to instead start or end the slice at the last ">" or the first "<" within the title if present.

that way the readability will much much better and it would cut down on title sizes.

**Comment by Gonksy** [comment]
Edge case: Twitter: need to slice the title at title="Twitter" instead.

**Comment by TheWoodenMan** [comment]
I'm going to try and crack this one tonight.

**Comment by TheWoodenMan** [comment]
Fixed by https://github.com/HoldUpFjord/Link-Manager/pull/33
for titles that are held in title="x"
