### ISSUE TITLE
Models or schemas for links and collections

### ISSUE THREAD

**Issue by Gonksy** [HoldUpFjord/Link-Manager#7]
I've started working on defining schemas for our links and collections holding these links.

**Comment by Gonksy** [comment]
Added timestamps to tab schema 
![image](https://user-images.githubusercontent.com/87082240/188219286-c15274e9-0a9a-4b8a-a095-957c80a03449.png)

**Comment by TheWoodenMan** [comment]
https://github.com/HoldUpFjord/Link-Manager/pull/15 
solved this
